run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - errcheck
    - stylecheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: internal/infrastructure/repository/mysql/.*
      linters:
        - gocyclo