run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - errcheck
    - stylecheck
    - gocritic

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck