run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - errcheck
    - stylecheck
    - gocritic

linters-settings:
  gocritic:
    settings:
      rangeExprCopy:
        sizeThreshold: 128

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
`*`

Коммит: 8d7326f1d2c3bc6fe1d84db4e2dd988ddaa3b5a2
`*`
Fix GolangCI-Lint YAML configuration

- Correct indentation for gocritic settings section
- Remove invalid parameter structure causing YAML parse error
- Verify configuration with linter CLI before committing
