run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  skip-dirs:
    - testdata

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - errcheck
    - stylecheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
