run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - errcheck
    - stylecheck
    - gocritic

linters-settings:
  gocritic:
    settings:
      rangeExprCopy:
        sizeThreshold: 128

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
