name: Code Quality Pipeline

on: 
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  code-lint:
    name: Code Linting and Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
          
      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          args: --config=.golangci.yml --timeout=5m ./internal/...
          install-mode: goinstall
