yaml
name: Database Schema Checks

on:
  workflow_run:
    workflows: ["Code Quality Assurance"]
    types: [completed]

jobs:
  schema-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Verify SQL schemas
        uses: sql-action/dbcheck@v1
        with:
          driver: mysql
          host: localhost
          port: 3306
          username: ${{ secrets.DB_USER }}
          password: ${{ secrets.DB_PASS }}
          schema: flexible_transfer_backend/init.sql