name: Database Schema Checks

on:
  workflow_run:
    workflows: ["Code Quality Assurance"]
    types: [completed]

jobs:
  schema-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify SQL schemas
        uses: sqlsmith-org/sql-action@v1
        with:
          engine: mysql
          host: ${{ secrets.DB_HOST }}
          port: 3306
          user: ${{ secrets.DB_USER }}
          password: ${{ secrets.DB_PASS }}
          database: flex_exchange
          schema: init.sql